# Generated by Django 5.1.7 on 2025-09-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerceptronTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del entrenamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('learning_rate', models.FloatField(verbose_name='Tasa de aprendizaje')),
                ('epochs', models.IntegerField(verbose_name='Número de épocas')),
                ('input_columns', models.JSONField(verbose_name='Columnas de entrada')),
                ('output_columns', models.JSONField(verbose_name='Columnas de salida')),
                ('final_weights', models.JSONField(verbose_name='Pesos finales')),
                ('final_bias', models.FloatField(verbose_name='Sesgo final')),
                ('accuracy', models.FloatField(verbose_name='Precisión final')),
                ('training_errors', models.JSONField(verbose_name='Errores por época')),
                ('weight_evolution', models.JSONField(verbose_name='Evolución de pesos')),
                ('data_file', models.FileField(upload_to='training_data/', verbose_name='Archivo de datos')),
            ],
            options={
                'verbose_name': 'Entrenamiento de Perceptrón',
                'verbose_name_plural': 'Entrenamientos de Perceptrón',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_values', models.JSONField(verbose_name='Valores de entrada')),
                ('predicted_output', models.FloatField(verbose_name='Salida predicha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de predicción')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='perceptron_app.perceptrontraining', verbose_name='Entrenamiento')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
