# Generated by Django 5.1.7 on 2025-09-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perceptrontraining',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='training_data/', verbose_name='Archivo de datos'),
        ),
    ]
