# Generated by Django 5.1.7 on 2025-09-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0002_alter_perceptrontraining_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='perceptrontraining',
            name='max_error',
            field=models.FloatField(default=0.1, verbose_name='Error máximo permitido'),
        ),
    ]
