# Generated by Django 5.1.7 on 2025-09-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0003_perceptrontraining_max_error'),
    ]

    operations = [
    ]
