# Generated by Django 5.1.7 on 2025-09-09 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0004_auto_20250908_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perceptrontraining',
            name='max_error',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MaxValueValidator(0.1)], verbose_name='Error máximo permitido'),
        ),
    ]
