# Generated by Django 5.1.7 on 2025-09-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0006_rename_fields_to_spanish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perceptrontraining',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Entrenamiento de Perceptrón', 'verbose_name_plural': 'Entrenamientos de Perceptrón'},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['-fecha_prediccion'], 'verbose_name': 'Predicción', 'verbose_name_plural': 'Predicciones'},
        ),
        migrations.AlterField(
            model_name='perceptrontraining',
            name='iteraciones',
            field=models.IntegerField(verbose_name='Número de iteraciones'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='entrenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='perceptron_app.perceptrontraining', verbose_name='Entrenamiento'),
        ),
    ]
