# Generated by Django 5.2.6 on 2025-09-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0007_alter_perceptrontraining_options_and_more'),
    ]

    operations = [
    ]
