# Generated by Django 5.1.7 on 2025-09-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0008_auto_20250910_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perceptrontraining',
            name='iteraciones',
            field=models.IntegerField(verbose_name='Número de iteraciones'),
        ),
    ]
