# Generated by Django 5.2.6 on 2025-09-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0009_auto_20250910_1528'),
    ]

    operations = [
    ]
