# Generated by Django 5.1.7 on 2025-09-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perceptron_app', '0010_fix_iteraciones_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='perceptrontraining',
            name='iteraciones',
            field=models.IntegerField(default=100, verbose_name='Número de iteraciones'),
            preserve_default=False,
        ),
    ]
