# Generated by Django 5.1.7 on 2025-09-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perceptron_app", "0011_fix_iteraciones_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="perceptrontraining",
            name="errores_patron",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Errores por patrón"
            ),
        ),
    ]
