# Generated by Django 5.1.7 on 2025-10-26 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RBFTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del entrenamiento"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "num_centros",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Número de centros radiales",
                    ),
                ),
                (
                    "porcentaje_entrenamiento",
                    models.FloatField(
                        default=70.0,
                        validators=[
                            django.core.validators.MinValueValidator(50.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="Porcentaje de entrenamiento",
                    ),
                ),
                (
                    "error_aproximacion",
                    models.FloatField(
                        default=0.1,
                        validators=[django.core.validators.MaxValueValidator(1.0)],
                        verbose_name="Error de aproximación óptimo",
                    ),
                ),
                (
                    "columnas_entrada",
                    models.JSONField(verbose_name="Columnas de entrada"),
                ),
                (
                    "columnas_salida",
                    models.JSONField(verbose_name="Columnas de salida"),
                ),
                (
                    "centros_radiales",
                    models.JSONField(verbose_name="Centros radiales (Rj)"),
                ),
                ("pesos_finales", models.JSONField(verbose_name="Pesos finales (W)")),
                ("umbral", models.FloatField(verbose_name="Umbral (W0)")),
                (
                    "metricas_entrenamiento",
                    models.JSONField(
                        verbose_name="Métricas de entrenamiento (EG, MAE, RMSE)"
                    ),
                ),
                (
                    "metricas_prueba",
                    models.JSONField(verbose_name="Métricas de prueba (EG, MAE, RMSE)"),
                ),
                (
                    "convergencia",
                    models.BooleanField(
                        default=False, verbose_name="Convergencia alcanzada"
                    ),
                ),
                (
                    "estadisticas_normalizacion",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Estadísticas de normalización (mean, std)",
                    ),
                ),
                (
                    "archivo_datos",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="rbf_training_data/",
                        verbose_name="Archivo de datos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrenamiento RBF",
                "verbose_name_plural": "Entrenamientos RBF",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
