# Generated by Django 5.1.7 on 2025-10-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RBFPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valores_entrada",
                    models.JSONField(verbose_name="Valores de entrada"),
                ),
                ("salida_predicha", models.FloatField(verbose_name="Salida predicha")),
                (
                    "fecha_prediccion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de predicción"
                    ),
                ),
                (
                    "entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicciones",
                        to="rbf.rbftraining",
                        verbose_name="Entrenamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción RBF",
                "verbose_name_plural": "Predicciones RBF",
                "ordering": ["-fecha_prediccion"],
            },
        ),
    ]
