# Generated by Django 5.1.7 on 2025-10-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbf", "0002_rbfprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="rbftraining",
            name="y_test_pred",
            field=models.JSONField(
                blank=True,
                help_text="Valores predichos (Y_pred) del conjunto de prueba",
                null=True,
                verbose_name="Valores predichos de prueba",
            ),
        ),
        migrations.AddField(
            model_name="rbftraining",
            name="y_test_real",
            field=models.JSONField(
                blank=True,
                help_text="Valores reales (Y) del conjunto de prueba",
                null=True,
                verbose_name="Valores reales de prueba",
            ),
        ),
        migrations.AddField(
            model_name="rbftraining",
            name="y_train_pred",
            field=models.JSONField(
                blank=True,
                help_text="Valores predichos (Y_pred) del conjunto de entrenamiento",
                null=True,
                verbose_name="Valores predichos de entrenamiento",
            ),
        ),
        migrations.AddField(
            model_name="rbftraining",
            name="y_train_real",
            field=models.JSONField(
                blank=True,
                help_text="Valores reales (Y) del conjunto de entrenamiento",
                null=True,
                verbose_name="Valores reales de entrenamiento",
            ),
        ),
    ]
