# Generated by Django 5.2.6 on 2025-11-12 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntrenamientoMLP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Entrenamiento"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "num_capas_ocultas",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Número de Capas Ocultas",
                    ),
                ),
                (
                    "neuronas_por_capa",
                    models.JSONField(
                        help_text="Lista con el número de neuronas por cada capa oculta, ej: [32, 16]",
                        verbose_name="Neuronas por Capa",
                    ),
                ),
                (
                    "funcion_activacion",
                    models.CharField(
                        choices=[
                            ("relu", "ReLU"),
                            ("sigmoid", "Sigmoid"),
                            ("tanh", "Tanh"),
                        ],
                        default="relu",
                        max_length=20,
                        verbose_name="Función de Activación",
                    ),
                ),
                (
                    "tasa_aprendizaje",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0001),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Tasa de Aprendizaje",
                    ),
                ),
                (
                    "iteraciones",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="Número de Iteraciones",
                    ),
                ),
                (
                    "porcentaje_entrenamiento",
                    models.FloatField(
                        default=70.0,
                        validators=[
                            django.core.validators.MinValueValidator(50.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                        verbose_name="Porcentaje de Entrenamiento",
                    ),
                ),
                (
                    "tamanio_batch",
                    models.IntegerField(
                        default=32,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(256),
                        ],
                        verbose_name="Tamaño de Batch",
                    ),
                ),
                (
                    "columnas_entrada",
                    models.JSONField(
                        help_text="Lista de nombres de columnas usadas como características",
                        verbose_name="Columnas de Entrada",
                    ),
                ),
                (
                    "columna_salida",
                    models.CharField(
                        choices=[("G1", "G1"), ("G2", "G2"), ("G3", "G3")],
                        max_length=50,
                        verbose_name="Columna de Salida",
                    ),
                ),
                (
                    "pesos_capas",
                    models.JSONField(
                        help_text="Lista de matrices de pesos para cada capa",
                        verbose_name="Pesos de las Capas",
                    ),
                ),
                (
                    "sesgos_capas",
                    models.JSONField(
                        help_text="Lista de vectores de sesgos para cada capa",
                        verbose_name="Sesgos de las Capas",
                    ),
                ),
                (
                    "precision_entrenamiento",
                    models.FloatField(
                        help_text="R² o precisión en el conjunto de entrenamiento",
                        verbose_name="Precisión de Entrenamiento",
                    ),
                ),
                (
                    "precision_validacion",
                    models.FloatField(
                        help_text="R² o precisión en el conjunto de validación",
                        verbose_name="Precisión de Validación",
                    ),
                ),
                (
                    "errores_entrenamiento",
                    models.JSONField(
                        help_text="Lista de errores por iteración en entrenamiento",
                        verbose_name="Errores de Entrenamiento",
                    ),
                ),
                (
                    "errores_validacion",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de errores por iteración en validación",
                        null=True,
                        verbose_name="Errores de Validación",
                    ),
                ),
                (
                    "metricas",
                    models.JSONField(
                        default=dict,
                        help_text="Diccionario con métricas: MAE, RMSE, R², etc.",
                        verbose_name="Métricas",
                    ),
                ),
                (
                    "archivo_modelo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="modelos_mlp/",
                        verbose_name="Archivo del Modelo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional del entrenamiento",
                        verbose_name="Descripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrenamiento MLP",
                "verbose_name_plural": "Entrenamientos MLP",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["-fecha_creacion"],
                        name="prediccion__fecha_c_795022_idx",
                    ),
                    models.Index(
                        fields=["columna_salida"], name="prediccion__columna_db7792_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacion",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Identificación"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "edad",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Edad",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        choices=[("U", "Urbano"), ("R", "Rural")],
                        max_length=10,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "tamano_familia",
                    models.CharField(
                        choices=[("GT3", "Mayor 3"), ("LE3", "Menor igual 3")],
                        max_length=3,
                        verbose_name="Tamaño de Familia",
                    ),
                ),
                (
                    "estado_padres",
                    models.CharField(
                        choices=[("T", "Juntos"), ("A", "Apartados")],
                        max_length=1,
                        verbose_name="Estado de los Padres",
                    ),
                ),
                (
                    "educacion_madre",
                    models.IntegerField(
                        choices=[
                            (0, "Ninguna"),
                            (1, "Primaria"),
                            (2, "5to-9no"),
                            (3, "Secundaria"),
                            (4, "Superior"),
                        ],
                        verbose_name="Educación de la Madre",
                    ),
                ),
                (
                    "educacion_padre",
                    models.IntegerField(
                        choices=[
                            (0, "Ninguna"),
                            (1, "Primaria"),
                            (2, "5to-9no"),
                            (3, "Secundaria"),
                            (4, "Superior"),
                        ],
                        verbose_name="Educación del Padre",
                    ),
                ),
                (
                    "trabajo_madre",
                    models.CharField(max_length=50, verbose_name="Trabajo de la Madre"),
                ),
                (
                    "trabajo_padre",
                    models.CharField(max_length=50, verbose_name="Trabajo del Padre"),
                ),
                (
                    "tiempo_viaje",
                    models.IntegerField(
                        help_text="1 (<15 min), 2 (15-30 min), 3 (30-60 min), 4 (>60 min)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Tiempo de Viaje",
                    ),
                ),
                (
                    "tiempo_estudio",
                    models.IntegerField(
                        help_text="1 (<2h), 2 (2-5h), 3 (5-10h), 4 (>10h)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Tiempo de Estudio",
                    ),
                ),
                (
                    "fallos_previos",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Fallos Previos",
                    ),
                ),
                (
                    "apoyo_escuela",
                    models.BooleanField(
                        default=False, verbose_name="Apoyo de la Escuela"
                    ),
                ),
                (
                    "apoyo_familia",
                    models.BooleanField(
                        default=False, verbose_name="Apoyo de la Familia"
                    ),
                ),
                (
                    "clases_pagadas",
                    models.BooleanField(default=False, verbose_name="Clases Pagadas"),
                ),
                (
                    "actividades_extra",
                    models.BooleanField(
                        default=False, verbose_name="Actividades Extraescolares"
                    ),
                ),
                (
                    "guarderia",
                    models.BooleanField(default=False, verbose_name="Guardería"),
                ),
                (
                    "quiere_superior",
                    models.BooleanField(
                        default=False, verbose_name="Quiere Estudios Superiores"
                    ),
                ),
                (
                    "internet",
                    models.BooleanField(default=False, verbose_name="Tiene Internet"),
                ),
                (
                    "relacion_romantica",
                    models.BooleanField(
                        default=False, verbose_name="Relación Romántica"
                    ),
                ),
                (
                    "relacion_familiar",
                    models.IntegerField(
                        help_text="1 (muy mala) - 5 (excelente)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Relación Familiar",
                    ),
                ),
                (
                    "tiempo_libre",
                    models.IntegerField(
                        help_text="1 (muy poco) - 5 (mucho)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Tiempo Libre",
                    ),
                ),
                (
                    "salidas",
                    models.IntegerField(
                        help_text="1 (muy poco) - 5 (mucho)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Salidas con Amigos",
                    ),
                ),
                (
                    "alcohol_semana",
                    models.IntegerField(
                        help_text="1 (muy bajo) - 5 (muy alto)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Consumo de Alcohol (Semana)",
                    ),
                ),
                (
                    "alcohol_fin_semana",
                    models.IntegerField(
                        help_text="1 (muy bajo) - 5 (muy alto)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Consumo de Alcohol (Fin de Semana)",
                    ),
                ),
                (
                    "salud",
                    models.IntegerField(
                        help_text="1 (muy mala) - 5 (excelente)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Salud",
                    ),
                ),
                (
                    "ausencias",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ausencias",
                    ),
                ),
                (
                    "calificacion_g1",
                    models.FloatField(
                        blank=True,
                        help_text="Calificación del primer período (0-20)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Calificación G1",
                    ),
                ),
                (
                    "calificacion_g2",
                    models.FloatField(
                        blank=True,
                        help_text="Calificación del segundo período (0-20)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Calificación G2",
                    ),
                ),
                (
                    "calificacion_g3",
                    models.FloatField(
                        blank=True,
                        help_text="Calificación del tercer período (0-20)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Calificación G3",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["identificacion"], name="prediccion__identif_7e5fa5_idx"
                    ),
                    models.Index(
                        fields=["-fecha_creacion"],
                        name="prediccion__fecha_c_67701c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PrediccionRendimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calificacion_predicha",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Calificación Predicha",
                    ),
                ),
                (
                    "calificacion_real",
                    models.FloatField(
                        blank=True,
                        help_text="Calificación real si está disponible para comparación",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Calificación Real",
                    ),
                ),
                (
                    "fecha_prediccion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Predicción"
                    ),
                ),
                (
                    "caracteristicas_usadas",
                    models.JSONField(
                        help_text="Diccionario con los valores de entrada usados para la predicción",
                        verbose_name="Características Usadas",
                    ),
                ),
                (
                    "error_prediccion",
                    models.FloatField(
                        blank=True,
                        help_text="Diferencia absoluta entre predicción y valor real (si está disponible)",
                        null=True,
                        verbose_name="Error de Predicción",
                    ),
                ),
                (
                    "entrenamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicciones",
                        to="prediccion_academica.entrenamientomlp",
                        verbose_name="Modelo de Entrenamiento",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicciones",
                        to="prediccion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción de Rendimiento",
                "verbose_name_plural": "Predicciones de Rendimiento",
                "ordering": ["-fecha_prediccion"],
            },
        ),
        migrations.CreateModel(
            name="AlertaEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_alerta",
                    models.CharField(
                        choices=[
                            ("bajo_rendimiento", "Bajo Rendimiento"),
                            ("alto_riesgo", "Alto Riesgo de Reprobación"),
                            ("mejora_necesaria", "Mejora Necesaria"),
                            ("ausencias_elevadas", "Ausencias Elevadas"),
                            ("prediccion_baja", "Predicción de Calificación Baja"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Alerta",
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Mensaje descriptivo de la alerta",
                        verbose_name="Mensaje",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "vista",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la alerta ha sido vista por un docente",
                        verbose_name="Vista",
                    ),
                ),
                (
                    "fecha_vista",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que la alerta fue vista",
                        null=True,
                        verbose_name="Fecha de Vista",
                    ),
                ),
                (
                    "prioridad",
                    models.IntegerField(
                        choices=[(1, "Baja"), (2, "Media"), (3, "Alta")],
                        default=1,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="prediccion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
                (
                    "prediccion_relacionada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas",
                        to="prediccion_academica.prediccionrendimiento",
                        verbose_name="Predicción Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Estudiante",
                "verbose_name_plural": "Alertas de Estudiantes",
                "ordering": ["-prioridad", "-fecha_creacion"],
            },
        ),
        migrations.AddIndex(
            model_name="prediccionrendimiento",
            index=models.Index(
                fields=["-fecha_prediccion"], name="prediccion__fecha_p_f88bea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediccionrendimiento",
            index=models.Index(
                fields=["estudiante"], name="prediccion__estudia_f77db3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediccionrendimiento",
            index=models.Index(
                fields=["entrenamiento"], name="prediccion__entrena_e909b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertaestudiante",
            index=models.Index(
                fields=["-fecha_creacion"], name="prediccion__fecha_c_5ab2f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertaestudiante",
            index=models.Index(
                fields=["estudiante"], name="prediccion__estudia_bc0fd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertaestudiante",
            index=models.Index(fields=["vista"], name="prediccion__vista_1dc985_idx"),
        ),
        migrations.AddIndex(
            model_name="alertaestudiante",
            index=models.Index(
                fields=["-prioridad"], name="prediccion__priorid_95e3b4_idx"
            ),
        ),
    ]
