# Generated by Django 5.2.6 on 2025-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prediccion_academica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrenamientomlp",
            name="info_preprocesamiento",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Información sobre transformaciones aplicadas (mapeo_categorias, mapeo_labels, columnas_finales, etc.)",
                null=True,
                verbose_name="Información de Preprocesamiento",
            ),
        ),
        migrations.AddField(
            model_name="entrenamientomlp",
            name="scaler_mean",
            field=models.JSONField(
                blank=True,
                help_text="Media de cada característica para normalización",
                null=True,
                verbose_name="Media del Scaler",
            ),
        ),
        migrations.AddField(
            model_name="entrenamientomlp",
            name="scaler_scale",
            field=models.JSONField(
                blank=True,
                help_text="Desviación estándar de cada característica para normalización",
                null=True,
                verbose_name="Escala del Scaler",
            ),
        ),
    ]
