# Generated by Django 5.2.6 on 2025-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prediccion_academica",
            "0002_entrenamientomlp_info_preprocesamiento_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entrenamientomlp",
            name="num_caracteristicas_finales",
            field=models.IntegerField(
                blank=True,
                help_text="Número de características después del preprocesamiento (one-hot encoding)",
                null=True,
                verbose_name="Número de Características Finales",
            ),
        ),
        migrations.AddField(
            model_name="entrenamientomlp",
            name="precision_entrenamiento_historial",
            field=models.JSONField(
                blank=True,
                help_text="Lista de precisión (R²) por iteración en entrenamiento",
                null=True,
                verbose_name="Historial de Precisión de Entrenamiento",
            ),
        ),
        migrations.AddField(
            model_name="entrenamientomlp",
            name="precision_validacion_historial",
            field=models.JSONField(
                blank=True,
                help_text="Lista de precisión (R²) por iteración en validación",
                null=True,
                verbose_name="Historial de Precisión de Validación",
            ),
        ),
    ]
