# Generated by Django 5.2.6 on 2025-11-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prediccion_academica",
            "0003_entrenamientomlp_num_caracteristicas_finales_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entrenamientomlp",
            name="historial_entrenamiento_tf",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Historial de entrenamiento de TensorFlow (loss, metrics por epoch)",
                null=True,
                verbose_name="Historial de Entrenamiento TensorFlow",
            ),
        ),
        migrations.AddField(
            model_name="entrenamientomlp",
            name="modelo_tensorflow",
            field=models.FileField(
                blank=True,
                help_text="Archivo del modelo TensorFlow serializado (.h5 o .keras)",
                null=True,
                upload_to="modelos_mlp/",
                verbose_name="Modelo TensorFlow",
            ),
        ),
        migrations.AddField(
            model_name="entrenamientomlp",
            name="tipo_implementacion",
            field=models.CharField(
                choices=[
                    ("numpy", "Implementación desde cero (NumPy)"),
                    ("tensorflow", "TensorFlow/Keras"),
                ],
                default="numpy",
                help_text="Tipo de implementación utilizada para entrenar el modelo",
                max_length=20,
                verbose_name="Tipo de Implementación",
            ),
        ),
        migrations.AlterField(
            model_name="entrenamientomlp",
            name="pesos_capas",
            field=models.JSONField(
                blank=True,
                help_text="Lista de matrices de pesos para cada capa (solo para implementación NumPy)",
                null=True,
                verbose_name="Pesos de las Capas",
            ),
        ),
        migrations.AlterField(
            model_name="entrenamientomlp",
            name="sesgos_capas",
            field=models.JSONField(
                blank=True,
                help_text="Lista de vectores de sesgos para cada capa (solo para implementación NumPy)",
                null=True,
                verbose_name="Sesgos de las Capas",
            ),
        ),
    ]
