# Generated by Django 5.2.6 on 2025-11-14 00:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prediccion_academica",
            "0004_entrenamientomlp_historial_entrenamiento_tf_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="estrato",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Estrato",
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="horas_trabajo_sem",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Horas de Trabajo Semanales"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="programa_academico",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Programa Académico"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="promedio_acumulado",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Promedio Acumulado"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="promedio_semestre_anterior",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Promedio Semestre Anterior"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="puntaje_icfes_global",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Puntaje ICFES Global"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="semestre_actual",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Semestre Actual"
            ),
        ),
        migrations.AddField(
            model_name="estudiante",
            name="trabaja_actualmente",
            field=models.BooleanField(
                default=False, verbose_name="Trabaja Actualmente"
            ),
        ),
        migrations.CreateModel(
            name="HistorialAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semestre",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "promedio",
                    models.FloatField(
                        help_text="Promedio ponderado del semestre (0-5)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Promedio Ponderado",
                    ),
                ),
                (
                    "porcentaje_asistencia",
                    models.FloatField(
                        default=1.0,
                        help_text="Porcentaje de asistencia del semestre (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Porcentaje de Asistencia",
                    ),
                ),
                (
                    "materias_reprobadas",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Materias Reprobadas",
                    ),
                ),
                (
                    "creditos_inscritos",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Créditos Inscritos",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_academico",
                        to="prediccion_academica.estudiante",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial Académico",
                "verbose_name_plural": "Historiales Académicos",
                "ordering": ["estudiante", "semestre"],
                "indexes": [
                    models.Index(
                        fields=["estudiante", "semestre"],
                        name="prediccion__estudia_4aa73e_idx",
                    ),
                    models.Index(
                        fields=["semestre"], name="prediccion__semestr_f36629_idx"
                    ),
                ],
                "unique_together": {("estudiante", "semestre")},
            },
        ),
    ]
