# Generated by Django 5.2.6 on 2025-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prediccion_academica",
            "0005_estudiante_estrato_estudiante_horas_trabajo_sem_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="calificacion_g1",
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="calificacion_g2",
        ),
        migrations.RemoveField(
            model_name="estudiante",
            name="calificacion_g3",
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="estado_padres",
            field=models.CharField(
                choices=[("T", "Juntos"), ("S", "Separados")],
                max_length=1,
                verbose_name="Estado de los Padres",
            ),
        ),
    ]
