# Generated by Django 5.2.6 on 2025-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prediccion_academica", "0006_remove_estudiante_calificacion_g1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrenamientomlp",
            name="columna_salida",
            field=models.CharField(
                choices=[("Y_promedio_sem_siguiente", "Y_promedio_sem_siguiente")],
                default="Y_promedio_sem_siguiente",
                max_length=50,
                verbose_name="Columna de Salida",
            ),
        ),
    ]
